-- Script to manually create Wallets table in stakeholders schema
-- Run this in PgAdmin if migration doesn't work

-- Make sure you're connected to the correct database (probably 'explorer-v1')

CREATE TABLE IF NOT EXISTS stakeholders."Wallets" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" bigint NOT NULL,
    "AdventureCoins" integer NOT NULL DEFAULT 0
);

-- Create unique index on UserId
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Wallets_UserId" 
ON stakeholders."Wallets" ("UserId");

-- Verify the table was created
SELECT * FROM stakeholders."Wallets";
